#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 17 14:30:56 2019

@author: laurapuckett
"""

6Cs.txt
7Cs.txt
7mixed.txt
aBadLetter.txt
aNumber.txt
empty.txt

def read_files():
    path = '/Users/laurapuckett/Documents/INF502/'
    chainList = []
    for i in ['first','second']:
        Done = False        
        while Done is False:             
            filename = input('Enter the name of the text file that contains the ' + i + ' chain:' )
            
            try:
                file = open((path + filename),'r')
                if filename[-4:] != '.txt':
                    raise ValueError
                    print('Not a .txt file. Must enter the name of a .txt file.')
                
            except (FileNotFoundError, ValueError):
                print(filename + ' does not exist.')
                
            else:
                content = file.read() 
                file.close()
                badChain = False
                for letter in content:
                    try:
                        if letter not in 'actgACTG':
                            raise ValueError()
                    except ValueError:
                        print('there is a :', letter, 'in fileA.')
                        print('Please provide another filename instead.')
                        badChain = True
                try:
                    if content == "":
                        raise ValueError()
                    except ValueError:
                        print('The file is empty. Please provide a file with a chain.')
                        badChain = True
                    
                if badChain is False:
                    Done = True
                    chainList.append(content)
                    
    return chainList
                

            
def get_chains():
    chainsGood = False
    while chainsGood is False:
        try:
            chainList = read_files()
            chainA,chainB = chainList[0],chainList[1]
            if len(chainA) != len(chainB):
                raise ValueError
            
        except ValueError:
            print('ERROR, must provide chains of equal length')
            
        else:
            chainsGood = True
    return (chainA, chainB)

        
            

        
def getMethod():
    method = input('Type 1 for the method of maximum matches, or '
               'type 2 for the method of longest continuous matches:')
    if(method == "1"):
        method = 'nMatch'
    elif(method == "2"):
        method = 'nContig'
    else:
        print('You must enter "1" or "2" for method.')
        exit
    return method
    
        
def getmaxShift(chainLength):
    maxShift = input('Enter the maximum spaces that the chain is allowd to shift by: ')
    maxShift = int(maxShift)
    if maxShift > (chainLength - 1):
        maxShift = chainLength - 1
    return maxShift


def compare_chains_nMatch(chainA, chainB):
    matches = 0
    for i in range(len(chainA)):
        if(chainA[i] == chainB[i]):
            matches = matches + 1
    return matches


def compare_chains_maxContig(chainA, chainB):
    longestContig = 0
    contig = 0
    for i in range(len(chainA)):
        if(chainA[i] == chainB[i]):
            contig = contig + 1
            if (contig > longestContig):
                    longestContig = contig
        else:
            contig = 0
            
    return longestContig

    
def shift(chainA, chainB, shifter):
    if shifter > 0:
        newchainA = '-'*shifter + chainA
        newchainB = chainB + '-'*shifter
    else:
        newchainA = chainA + '-'*abs(shifter)
        newchainB = '-'*abs(shifter) + chainB
    return (newchainA, newchainB)

    
def findMaxMatches(chainA, chainB, maxShift, method):
    maxMatches = 0
    bestShift = 'NA'
    for shiftNum in range(-1*maxShift, maxShift):
        shiftedA, shiftedB = shift(chainA, chainB, shiftNum)
        
        if(method == 'nMatch'):
            matches = compare_chains_maxContig(shiftedA, shiftedB)
            
        if(method == 'nContig'):
            matches = compare_chains_nMatch(shiftedA, shiftedB)
            
        if matches >= maxMatches:
            maxMatches = matches
            bestShift = shiftNum
            bestShiftedA = shiftedA
            bestShiftedB = shiftedB
            
    return (maxMatches, bestShift, bestShiftedA, bestShiftedB)


def printOutput(method, maxMatches, bestShift, bestShiftedA, bestShiftedB, chainA, chainB):
    print()
    if(method == 'nMatch'):
        print('The maximum number of matches is: ' + str(maxMatches))
    
    elif(method == 'nContig'):
        print('The longest contiguous matching chain is: ' + str(maxMatches))
    
    if (maxMatches > 0):
    
        if(bestShift >0):
            print('This occurs when the first chain is shifted ' + str(bestShift) + ' spaces to the right.')
    
        elif(bestShift == 0):
            print('This occurs when there is no shift.')
    
        else:
            print('This occurs when the first chain is shifted ' + str(abs(bestShift)) + ' spaces to the left.')
    
    
        if(method == 'nMatch'):
            print('The chain shift with the greatest number of matches is shown below')
        elif(method == 'nContig'):
            print('The chain shift with the greatest length of contiguous matches is shown below')
        print(bestShiftedA)
        print(bestShiftedB)
        
    else:
        print('The two original chains are: ')
        print(chainA)
        print(chainB)


def main():
## need to get chainA, chainB from file1 and file2
    chainA, chainB = get_chains()
    chainLength = len(chainA)

    method = getMethod()
    
    maxShift = getmaxShift(chainLength)
    
    maxMatches, bestShift, bestShiftedA, bestShiftedB = findMaxMatches(chainA, chainB, maxShift, method)
    printOutput(method, maxMatches, bestShift, bestShiftedA, bestShiftedB, chainA, chainB)

# file1 = '/Users/laurapuckett/Documents/INF502/file1.txt'
# file2 = '/Users/laurapuckett/Documents/INF502/file2.txt'
# maxShift = 10
# method = 'nMatch'

main()
